-- Inserindo ALUNO
INSERT INTO ALUNO (NOME, SEXO) VALUES ('Carlos Silva', 'M');
INSERT INTO ALUNO (NOME, SEXO) VALUES ('Ana Souza', 'F');
INSERT INTO ALUNO (NOME, SEXO) VALUES ('Mariana Costa', 'F');
INSERT INTO ALUNO (NOME, SEXO) VALUES ('João Pereira', 'M');

-- Inserindo AUTOR
INSERT INTO AUTOR (NOME) VALUES ('Machado de Assis');
INSERT INTO AUTOR (NOME) VALUES ('J. K. Rowling');
INSERT INTO AUTOR (NOME) VALUES ('George Orwell');
INSERT INTO AUTOR (NOME) VALUES ('Paulo Coelho');

-- Inserindo EDITORA
INSERT INTO EDITORA (NOME) VALUES ('Companhia das Letras');
INSERT INTO EDITORA (NOME) VALUES ('Rocco');
INSERT INTO EDITORA (NOME) VALUES ('Penguin Books');
INSERT INTO EDITORA (NOME) VALUES ('HarperCollins');

-- Inserindo LIVRO
INSERT INTO LIVRO (TIPO, TITULO, AREARALECIONADA, ANOPUBLICACAO, ISSN, ID_AUTOR, ID_EDITORA)
VALUES ('R', 'Dom Casmurro', 'Literatura Brasileira', '1899-01-01', '1234-5678', 1, 1);

INSERT INTO LIVRO (TIPO, TITULO, AREARALECIONADA, ANOPUBLICACAO, ISSN, ID_AUTOR, ID_EDITORA)
VALUES ('F', 'Harry Potter e a Pedra Filosofal', 'Fantasia', '1997-06-26', '2345-6789', 2, 2);

INSERT INTO LIVRO (TIPO, TITULO, AREARALECIONADA, ANOPUBLICACAO, ISSN, ID_AUTOR, ID_EDITORA)
VALUES ('R', '1984', 'Distopia', '1949-06-08', '3456-7890', 3, 3);

INSERT INTO LIVRO (TIPO, TITULO, AREARALECIONADA, ANOPUBLICACAO, ISSN, ID_AUTOR, ID_EDITORA)
VALUES ('R', 'O Alquimista', 'Filosofia', '1988-01-01', '4567-8901', 4, 4);

-- Inserindo EMPRESTIMO
INSERT INTO EMPRESTIMO (ID_ALUNO, ID_LIVRO, DATAEMPRESTIMO, DATADEVOLUCAO)
VALUES (1, 2, '2025-09-01 10:00:00', '2025-09-15 10:00:00');

INSERT INTO EMPRESTIMO (ID_ALUNO, ID_LIVRO, DATAEMPRESTIMO, DATADEVOLUCAO)
VALUES (2, 1, '2025-09-05 14:00:00', '2025-09-20 14:00:00');

INSERT INTO EMPRESTIMO (ID_ALUNO, ID_LIVRO, DATAEMPRESTIMO, DATADEVOLUCAO)
VALUES (3, 4, '2025-09-10 09:30:00', NULL);

INSERT INTO EMPRESTIMO (ID_ALUNO, ID_LIVRO, DATAEMPRESTIMO, DATADEVOLUCAO)
VALUES (4, 3, '2025-09-12 16:45:00', NULL);