-- Tabela ALUNO
CREATE TABLE IF NOT EXISTS ALUNO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    SEXO CHAR(1)
);

-- Tabela AUTOR
CREATE TABLE IF NOT EXISTS AUTOR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL
);

-- Tabela EDITORA
CREATE TABLE IF NOT EXISTS EDITORA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL
);

-- Tabela LIVRO (com referências para AUTOR e EDITORA)
CREATE TABLE IF NOT EXISTS LIVRO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIPO CHAR,
    TITULO TEXT NOT NULL,
    AREARALECIONADA TEXT,
    ANOPUBLICACAO DATE,
    ISSN TEXT,
    ID_AUTOR INTEGER NOT NULL,
    ID_EDITORA INTEGER NOT NULL,
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID),
    FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA(ID)
);

-- Tabela EMPRESTIMO
CREATE TABLE IF NOT EXISTS EMPRESTIMO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ALUNO INTEGER NOT NULL,
    ID_LIVRO INTEGER NOT NULL,
    DATAEMPRESTIMO TIMESTAMP,
    DATADEVOLUCAO TIMESTAMP,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID)
);