--DELETA AS TABELAS CASO EXISTAM
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS LIVRO;
DROP TABLE IF EXISTS EMPRESTIMO;

CREATE TABLE IF NOT EXISTS ALUNO (
    METRICULA INTEGER PRIMARY KEY,
    NOME TEXT NOT NULL,
    TURMA TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    TELEFONE TEXT NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    STATUS TEXT NOT NULL  
);

CREATE TABLE IF NOT EXISTS LIVRO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITULO TEXT NOT NULL,   
    AUTOR TEXT NOT NULL,
    CATEGORIA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPRESTIMO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ALUNO INTEGER NOT NULL,
    ID_LIVRO INTEGER NOT NULL,
    DATAEMPRESTIMO TIMESTAMP,
    DATADEVOLUCAO TIMESTAMP,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID)
);